# Generated by Django 4.2.17 on 2024-12-08 17:45

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Users",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "last_login",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="last login"
                    ),
                ),
                ("firstName", models.CharField(max_length=100, null=True)),
                ("lastName", models.CharField(max_length=100, null=True)),
                ("email", models.EmailField(max_length=100, null=True)),
                ("password", models.CharField(max_length=100, null=True)),
            ],
            options={
                "db_table": "users",
            },
        ),
    ]
