# Generated by Django 4.2.17 on 2024-12-10 07:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0002_userqueries"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userqueries",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="users.users"
            ),
        ),
    ]
